# Generated by Django 4.1.4 on 2022-12-14 19:40

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(help_text='Необходимо указывать в см', max_length=3, validators=[apps.users.validators.validate_height_weight], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(help_text='Необходимо указывать в кг', max_length=3, validators=[apps.users.validators.validate_height_weight], verbose_name='Вес'),
        ),
    ]
